{"name": "test_length[params0]", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'NoneType' and 'int'", "trace": "self = <test_cal.test_case.test_add.TestAdd object at 0x000001CF3E6B64C0>\nparams = {'data': {'a': None, 'b': 1.0}, 'name': 'a为空', 'validate': '报错啦'}\n\n    @pytest.mark.add\n    @pytest.mark.p1\n    @pytest.mark.parametrize(\"params\", read_yaml(\"./data/add_length.yaml\"))\n    def test_length(self, params):\n        \"\"\"\n        测试输入参数的长度\n        :param params: a,b,validate\n        :return:\n        \"\"\"\n        cal = Calculator()\n>       result = cal.add(params[\"data\"]['a'], params[\"data\"]['b'])\n\ntest_case\\test_add.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <calculator.Calculator object at 0x000001CF3E6B6D30>, a = None, b = 1.0\n\n    def add(self, a, b):\n>       if a > 99 or a < -99 or b > 99 or b < -99:\nE       TypeError: '>' not supported between instances of 'NoneType' and 'int'\n\n..\\calculator.py:8: TypeError"}, "description": "\n        测试输入参数的长度\n        :param params: a,b,validate\n        :return:\n        ", "parameters": [{"name": "params", "value": "{'name': 'a为空', 'data': {'a': None, 'b': 1.0}, 'validate': '报错啦'}"}], "start": 1649946102186, "stop": 1649946102186, "uuid": "1a810703-4f3d-4167-95b2-29fa7d74638b", "historyId": "c94c2fe3273000ae3c72522ac068000a", "testCaseId": "18fc6f6f5dac2aec77cfa2769d0346e9", "fullName": "test_case.test_add.TestAdd#test_length", "labels": [{"name": "tag", "value": "p1"}, {"name": "tag", "value": "add"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_add"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "Daisy"}, {"name": "thread", "value": "3516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_add"}]}